name: build with docker

on:
  push:
    branches:
      - main
      - develop
      - release

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: rootpassword
          MYSQL_DATABASE: world_db
          MYSQL_USER: user
          MYSQL_PASSWORD: password
        ports:
          - 0:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build and package application with Maven
        run: mvn clean package -DskipTests

          # Install Docker Compose
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      # Verify Docker Compose is installed
      - name: Verify Docker Compose version
        run: docker-compose --version

      - name: Build Docker image
        run: docker build -t reportsappimage .

      - name: Start services with Docker Compose
        run: docker-compose up --build -d

      - name: Run tests
        run: |
          sleep 40  # Wait for the containers to be ready
          curl --fail http://localhost:8080/actuator/health

      - name: Stop and clean up Docker containers
        run: docker-compose down
